version: 2
formats: all
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
build:
  os: ubuntu-20.04
  tools:
    python: "3"
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
